// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_Ns-eIvamkfONcVll-012MKW6tOj9bs',
    appId: '1:626301594254:android:807a7d655eeaf755bfb7df',
    messagingSenderId: '626301594254',
    projectId: 'connect-katham',
    storageBucket: 'connect-katham.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQLEOGre0T9O68VwFpxUmEVcdiDXLDM0',
    appId: '1:626301594254:ios:2cb2cbc6d4537274bfb7df',
    messagingSenderId: '626301594254',
    projectId: 'connect-katham',
    storageBucket: 'connect-katham.appspot.com',
    androidClientId: '626301594254-649kmafajvatjmlr35boci3ild13punn.apps.googleusercontent.com',
    iosClientId: '626301594254-bmninvhjjqso0o3ckfr1u3tsbrtlbp69.apps.googleusercontent.com',
    iosBundleId: 'com.aryan.connect.connect',
  );
}
